Docker works on my end
Access-Point-Program/cohort-3-dashboard pull request #96
Opened 2023-12-19 15:26 UTC by nickjansen12312

# Description

Got docker working on my end.

## Checklist

- [ ] meet all requirements of the client
- [ ] A proportionate amount of tests created
- [ ] tests passed
- [ ] peer review
- [ ] refactored and readable 
- [ ] detailed comments where need be

2023-12-19 15:40 UTC, chris-marfia requested changes
I provided suggestions on what lines of code you can delete

2023-12-19 15:40 UTC, chris-marfia commented on src/main/java/com/example/dashboard/configuration/RestConfiguration.java
> +
You can delete these three lines.

```suggestion
```

2023-12-19 15:40 UTC, chris-marfia commented on src/main/java/com/example/dashboard/controllers/LayoutController.java
> +import com.example.dashboard.configuration.AccessPointProperties;
You can delete this line.

```suggestion
```

2023-12-19 15:40 UTC, chris-marfia commented on src/main/java/com/example/dashboard/controllers/LayoutController.java
> +
You can delete this line.

```suggestion
```

2023-12-19 15:40 UTC, chris-marfia commented on src/main/java/com/example/dashboard/controllers/LayoutController.java
> +        accessPointProperties.getLayoutsApiUrl();
You can delete this line.

```suggestion
```

2023-12-19 15:40 UTC, chris-marfia commented on src/main/java/com/example/dashboard/controllers/LayoutController.java
> +        accessPointProperties.getLayoutsApiUrl();
You can delete this line.

```suggestion
```

2023-12-19 15:40 UTC, chris-marfia commented on src/main/java/com/example/dashboard/controllers/RuleSetsController.java
> +import com.example.dashboard.configuration.AccessPointProperties;
You can delete this line.

```suggestion
```

2023-12-19 15:40 UTC, chris-marfia commented on src/main/java/com/example/dashboard/controllers/RuleSetsController.java
> +
You can delete this line.

```suggestion
```

2023-12-19 15:40 UTC, chris-marfia commented on src/main/java/com/example/dashboard/controllers/RuleSetsController.java
> +        accessPointProperties.getRulesApiUrl();
You can delete this line.

```suggestion
```

2023-12-19 15:40 UTC, chris-marfia commented on src/main/java/com/example/dashboard/controllers/RuleSetsController.java
> +        accessPointProperties.getRulesApiUrl();
You can delete this line.

```suggestion
```

2023-12-19 15:40 UTC, chris-marfia commented on src/main/resources/application.properties
> +
You can delete this since you are not using it. 

```suggestion
```

2023-12-19 20:30 UTC, DemetriosDubis approved these changes
Changes made, everything ran on our end.  

Noah was having JDK issues, unrelated to the docker issue.

2023-12-21 20:07 UTC, nickjansen12312 reviewed
looks good

2024-01-02 16:15 UTC, chris-marfia approved these changes

2024-01-02 16:19 UTC, merged